const cabinetDb=new Dexie('TerritoryCabinetDB');
cabinetDb.version(1).stores({timeEntries:'++id, startedAt, endedAt, category',tabs:'++id, title, url, createdAt',settings:'key'});
const CACHE_KEY='territory-cabinet-tracker-cache-v2',PROFILE_KEY='territory-cabinet-profile-v1';
const $=id=>document.getElementById(id),pad=n=>String(n).padStart(2,'0');
let activeView='home',activeTab=null,ticker=null;
let trackerCache=readJson(CACHE_KEY,{entries:[],running:null});
trackerCache.entries=Array.isArray(trackerCache.entries)?trackerCache.entries:[];
trackerCache.running=trackerCache.running||null;
let profile=readJson(PROFILE_KEY,{name:''});
let running=trackerCache.running||null;
function readJson(key,fallback){try{return JSON.parse(localStorage.getItem(key))||fallback}catch{return fallback}}
function saveCache(){trackerCache.running=running;localStorage.setItem(CACHE_KEY,JSON.stringify(trackerCache))}
const localDay=value=>{const d=new Date(value);return `${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`};
const durationText=value=>{const s=Math.max(0,Math.floor(value));return `${Math.floor(s/3600)}:${pad(Math.floor(s%3600/60))}:${pad(s%60)}`};
const clockText=durationText;
function updateDate(){const now=new Date();$('todayDate').textContent=new Intl.DateTimeFormat('uk-UA',{day:'numeric',month:'long',year:'numeric'}).format(now);$('todayWeekday').textContent=new Intl.DateTimeFormat('uk-UA',{weekday:'long'}).format(now)}
function renderProfile(){const name=profile.name.trim()||'Мій кабінет';$('userNameLabel').textContent=name;$('userNameInput').value=profile.name||''}
async function hydrateCache(){try{const dbEntries=await cabinetDb.timeEntries.orderBy('createdAt').reverse().toArray();if(!trackerCache.entries.length&&dbEntries.length){trackerCache.entries=dbEntries.map(e=>({...e,cacheId:e.cacheId||`legacy-${e.id}`}));saveCache()}const saved=await cabinetDb.settings.get('runningTimer');if(!running&&saved?.value){running=saved.value;saveCache()}}catch{ /* localStorage cache remains available even if IndexedDB is blocked */ }}
function elapsed(){if(!running)return 0;return running.pausedAt?Number(running.elapsedBefore||0):Math.floor((Date.now()-running.startedAt)/1000)+Number(running.elapsedBefore||0)}
function setTimerUi(){const seconds=elapsed();$('timerDisplay').textContent=clockText(seconds);$('timerState').textContent=!running?'ГОТОВИЙ':running.pausedAt?'НА ПАУЗІ':'ВИКОНУЄТЬСЯ';$('startTimerBtn').textContent=running?'■ Зберегти запис':'▶ Почати';$('pauseTimerBtn').disabled=!running;$('pauseTimerBtn').textContent=running?.pausedAt?'▶':'Ⅱ'}
function startTicker(){clearInterval(ticker);ticker=setInterval(()=>{setTimerUi();renderTimeTotals()},500)}
async function mirrorRunning(){saveCache();try{if(running)await cabinetDb.settings.put({key:'runningTimer',value:running});else await cabinetDb.settings.delete('runningTimer')}catch{}}
async function toggleTimer(){const task=$('taskInput').value.trim()||'Без назви';if(!running){running={task,startedAt:Date.now(),firstStartedAt:Date.now(),elapsedBefore:0};await mirrorRunning();startTicker();setTimerUi();return}const seconds=elapsed();if(seconds>0){const entry={cacheId:`entry-${Date.now()}-${Math.random().toString(16).slice(2)}`,category:running.task,startedAt:running.firstStartedAt||running.startedAt,endedAt:Date.now(),duration:seconds,createdAt:Date.now()};trackerCache.entries.unshift(entry);running=null;saveCache();try{await cabinetDb.timeEntries.add(entry)}catch{}}else running=null;clearInterval(ticker);await mirrorRunning();setTimerUi();renderEntries();renderOverview()}
async function togglePauseTimer(){if(!running)return;if(running.pausedAt){running.startedAt=Date.now();delete running.pausedAt}else{running.elapsedBefore=elapsed();running.pausedAt=Date.now()}await mirrorRunning();setTimerUi()}
async function resetTimer(){if(!running)return;if(!confirm('Скинути поточний трекер без збереження запису?'))return;running=null;clearInterval(ticker);await mirrorRunning();$('taskInput').value='';setTimerUi();renderTimeTotals()}
function allEntries(){return [...trackerCache.entries].sort((a,b)=>b.createdAt-a.createdAt)}
function totals(){const entries=allEntries(),today=localDay(Date.now()),weekStart=Date.now()-6*86400000;const live=running&&localDay(running.firstStartedAt||running.startedAt)===today?elapsed():0;return{entries,today:entries.filter(e=>localDay(e.createdAt)===today).reduce((n,e)=>n+e.duration,0)+live,week:entries.filter(e=>e.createdAt>=weekStart).reduce((n,e)=>n+e.duration,0)+live}}
function renderTimeTotals(){const t=totals();$('summaryToday').textContent=durationText(t.today);$('summaryWeek').textContent=durationText(t.week);$('todayTotal').textContent=durationText(t.today);const count=t.entries.filter(e=>localDay(e.createdAt)===localDay(Date.now())).length;$('todayEntryCount').textContent=`${count} ${word(count,'запис','записи','записів')}`}
function showView(view){activeView=view;document.querySelectorAll('.view').forEach(el=>el.classList.remove('active'));$(`${view}View`).classList.add('active');document.querySelectorAll('.nav-item[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));const user=profile.name.trim();const headers={home:['КАБІНЕТ',user?`Доброго дня, ${user}`:'Доброго дня'],map:['РОБОЧА ВКЛАДКА','Карта територій'],time:['ОСОБИСТИЙ ТРЕКЕР','Час і записи'],chart:['ВБУДОВАНА ВКЛАДКА','Графік'],stand:['ВБУДОВАНА ВКЛАДКА','Стенд'],custom:['ДОДАТКОВА ВКЛАДКА',activeTab?.title||'Вкладка']};$('crumb').innerHTML=`<small>${headers[view][0]}</small><h1>${headers[view][1]}</h1>`;if(view==='time')renderEntries();if(view==='home')renderOverview();if(view==='custom')renderCustomTab();$('sidebar').classList.remove('open')}
async function renderTabs(){const tabs=await cabinetDb.tabs.orderBy('createdAt').toArray();$('customTabs').innerHTML=tabs.map(tab=>`<div class="custom-nav"><button class="nav-item" data-tab-id="${tab.id}" title="${escapeHtml(tab.title)}"><span>▧</span> ${escapeHtml(tab.title)}</button><button class="remove-nav" data-remove-tab="${tab.id}" title="Видалити">×</button></div>`).join('');const total=tabs.length+2;$('customTabCount').textContent=`${total} ${word(total,'вкладка','вкладки','вкладок')}`;document.querySelectorAll('[data-tab-id]').forEach(b=>b.onclick=()=>{activeTab=tabs.find(t=>t.id===Number(b.dataset.tabId));showView('custom')});document.querySelectorAll('[data-remove-tab]').forEach(b=>b.onclick=async e=>{e.stopPropagation();const tab=tabs.find(t=>t.id===Number(b.dataset.removeTab));if(confirm(`Видалити вкладку «${tab.title}»?`)){await cabinetDb.tabs.delete(tab.id);if(activeTab?.id===tab.id)showView('home');renderTabs()}})}
function renderCustomTab(){if(!activeTab)return showView('home');$('customTitle').textContent=activeTab.title;$('customUrl').textContent=activeTab.url;$('resourceFrame').src=activeTab.url;$('resourceEmpty').style.display='none'}
async function deleteEntry(cacheId){const entry=trackerCache.entries.find(item=>item.cacheId===cacheId);if(!entry||!confirm(`Видалити запис «${entry.category}»?`))return;trackerCache.entries=trackerCache.entries.filter(item=>item.cacheId!==cacheId);saveCache();try{const stored=(await cabinetDb.timeEntries.toArray()).find(item=>item.cacheId===cacheId||(!item.cacheId&&`legacy-${item.id}`===cacheId));if(stored)await cabinetDb.timeEntries.delete(stored.id)}catch{}renderEntries();renderOverview()}
function renderEntries(){const entries=allEntries();renderTimeTotals();$('entriesList').innerHTML=entries.length?entries.map(e=>`<div class="entry"><span class="entry-icon">◷</span><div><b>${escapeHtml(e.category)}</b><small>${new Intl.DateTimeFormat('uk-UA',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(e.createdAt)}</small></div><time>${new Intl.DateTimeFormat('uk-UA',{weekday:'short'}).format(e.createdAt)}</time><span class="entry-duration">${durationText(e.duration)}</span><button class="delete-entry" data-entry-id="${e.cacheId}" title="Видалити запис" aria-label="Видалити запис">×</button></div>`).join(''):'<p class="empty-copy">Тут з’являться завершені записи.</p>';document.querySelectorAll('[data-entry-id]').forEach(button=>button.onclick=()=>deleteEntry(button.dataset.entryId))}
function renderOverview(){const entries=allEntries();renderTimeTotals();$('recentList').innerHTML=entries.slice(0,4).map(e=>`<div class="recent-item"><span class="recent-mark">◷</span><div><b>${escapeHtml(e.category)}</b><small>${new Intl.DateTimeFormat('uk-UA',{day:'numeric',month:'long',hour:'2-digit',minute:'2-digit',second:'2-digit'}).format(e.createdAt)}</small></div><time>${durationText(e.duration)}</time></div>`).join('')||'<p class="empty-copy">Ще немає записів. Запусти перший трекер.</p>'}
function word(n,one,few,many){const k=n%10,n100=n%100;return k===1&&n100!==11?one:k>=2&&k<=4&&(n100<12||n100>14)?few:many}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openTabModal(){$('tabModal').classList.remove('hidden');$('tabTitleInput').focus()}
function openProfileModal(){$('profileModal').classList.remove('hidden');$('userNameInput').focus()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>showView(b.dataset.view));document.querySelectorAll('[data-open-view]').forEach(b=>b.onclick=()=>showView(b.dataset.openView));$('addTabBtn').onclick=openTabModal;$('quickAddTab').onclick=openTabModal;$('closeModal').onclick=()=>$('tabModal').classList.add('hidden');$('tabModal').onclick=e=>{if(e.target===$('tabModal'))$('tabModal').classList.add('hidden')};$('tabForm').onsubmit=async e=>{e.preventDefault();const title=$('tabTitleInput').value.trim(),url=$('tabUrlInput').value.trim();if(!title||!url)return;await cabinetDb.tabs.add({title,url,createdAt:Date.now()});e.target.reset();$('tabModal').classList.add('hidden');renderTabs()};$('profileBtn').onclick=openProfileModal;$('closeProfileModal').onclick=()=>$('profileModal').classList.add('hidden');$('profileModal').onclick=e=>{if(e.target===$('profileModal'))$('profileModal').classList.add('hidden')};$('profileForm').onsubmit=e=>{e.preventDefault();profile={name:$('userNameInput').value.trim()};localStorage.setItem(PROFILE_KEY,JSON.stringify(profile));renderProfile();$('profileModal').classList.add('hidden');showView(activeView)};$('startTimerBtn').onclick=toggleTimer;$('resetTimerBtn').onclick=resetTimer;$('pauseTimerBtn').onclick=togglePauseTimer;$('clearEntriesBtn').onclick=async()=>{if(confirm('Очистити всі завершені записи трекера?')){trackerCache.entries=[];saveCache();try{await cabinetDb.timeEntries.clear()}catch{}renderEntries();renderOverview()}};$('removeCustomTab').onclick=async()=>{if(activeTab&&confirm(`Видалити вкладку «${activeTab.title}»?`)){await cabinetDb.tabs.delete(activeTab.id);activeTab=null;await renderTabs();showView('home')}};$('mobileMenu').onclick=()=>$('sidebar').classList.toggle('open');
async function init(){updateDate();renderProfile();await hydrateCache();setTimerUi();await renderTabs();renderOverview();renderEntries();if(running)startTicker()}
init();
